// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heiqrkzfroxyngexvhdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlaXFya3pmcm94eW5nZXh2aGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Nzg2MTYsImV4cCI6MjA3MjI1NDYxNn0.otOdmg6LzR8djoCRg0mbZUBFnr8XRLZvSFNpQL-EG9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});